# Pandas
Open Source high-performance, easy-to-use data structures and data analysis tools

In [3]:
import pandas as pd

## Dataframe
A 2d tabular data structure with labellednrows and columns.  
- Label based indexing
- fast vectorized operations 
- built on numpy

In [3]:
data = {
    'Name':['Oscar Piastri','Arvid','Gorge Rusell'],
    'Age' :[27,18,28],
    'Country':['Italy','Britain','UK']
}

df=pd.DataFrame([[1,2,3],[3,4,5],[5,6,7]],columns=["A","B","C"])
print(df)

df=pd.DataFrame(data)
print(df)

df = pd.read_csv("customers-100.csv")
print(df.head())

#load from excel using pd.read_excel()

   A  B  C
0  1  2  3
1  3  4  5
2  5  6  7
            Name  Age  Country
0  Oscar Piastri   27    Italy
1          Arvid   18  Britain
2   Gorge Rusell   28       UK
   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter
1      2  1Ef7b82A4CAAD10    Preston    Lozano
2      3  6F94879bDAfE5a6        Roy     Berry
3      4  5Cef8BFA16c5e3c      Linda     Olsen
4      5  053d585Ab6b3159     Joanna    Bender

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan         Bensonview
4         Martin, Lang and Andrade     West Priscilla

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/

## Basic Commands

In [4]:

print(df.describe(), end='\n\n')

print(df.nunique(), end='\n\n')

print(df['City'].unique()[:5], end='\n\n')

print(df.info(), end='\n\n')

print(df.shape, end='\n\n')

print(df.tail(3))

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

Index                100
Customer Id          100
First Name            93
Last Name             97
Company               99
City                 100
Country               85
Phone 1              100
Phone 2              100
Email                100
Subscription Date     96
Website              100
dtype: int64

<ArrowStringArray>
[     'East Leonard', 'East Jimmychester',     'Isabelborough',
        'Bensonview',    'West Priscilla']
Length: 5, dtype: str

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    str
 2   First Name         100 non-null    str
 3   Last Name          100 non-null    str
 4   Company            100 non-null    str
 5   City               100 non-null    str
 6   Country            100 non-null    str
 7   Phone 1            100 non-null    str
 8   Phone 2            100 non-null    str
 9   Email              100 non-null    str
 10  Subscription Date  100 non-null    str
 11  Website            100 non-null    str
dtypes: int64(1), str(11)
memory usage: 24.7 KB
None

(100, 12)

    Index      Customer Id First Name Last Name             Company  \
97     98  28CDbC0dFe4b1Db       Fred    Guerra       Schmitt-Jones
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer  Fitzgerald-Harrell
99    100  2354a0E336A91A1   Clarence    Haynes  Le, Nash and Cross

               City          Country               Phone 1  \
97       Ortegaland  Solomon Islands  +1-753-067-8419x7170
98  Lake Elijahview            Aruba         (530)311-9786
99        Judymouth         Honduras         (753)813-6941

                   Phone 2                           Email Subscription Date  \
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

### loc

In [5]:
#df.loc[rows, columns]
print(df.loc[0])

print(df.loc[[0,1,5]])

print(df.loc[8:10])

print(df.loc[5:6,["City","Country"]])

Index                                         1
Customer Id                     DD37Cf93aecA6Dc
First Name                               Sheryl
Last Name                                Baxter
Company                         Rasmussen Group
City                               East Leonard
Country                                   Chile
Phone 1                            229.077.5154
Phone 2                        397.884.0519x718
Email                  zunigavanessa@smith.info
Subscription Date                    2020-08-24
Website              http://www.stephenson.com/
Name: 0, dtype: object
   Index      Customer Id First Name Last Name          Company  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter  Rasmussen Group
1      2  1Ef7b82A4CAAD10    Preston    Lozano      Vega-Gentry
5      6  2d08FB17EE273F4      Aimee     Downs     Steele Group

                City                 Country              Phone 1  \
0       East Leonard                   Chile         229.077.5154
1  East Jimmychester                Djibouti           5153435776
5      Chavezborough  Bosnia and Herzegovina  (283)437-3886x88321

            Phone 2                     Email Subscription Date  \
0  397.884.0519x718  zunigavanessa@smith.info        2020-08-24
1  686-620-1820x944           vmata@colon.com        2021-04-23
5      999-728-1637       louis27@gilbert.com        2020-02-25

                      Website
0  http://www.stephenson.com/
1       http://www.hobbs.com/
5      http://www.berger.net/
    Index      Customer Id First Name  Last Name                     Company  \
8       9  C2dE4dEEc489ae0     Sheryl     Meyers              Browning-Simon
9      10  8C2811a503C7c5a   Michelle  Gallagher                Beck-Hendrix
10     11  216E205d6eBb815       Carl  Schroeder  Oconnell, Meza and Everett

            City      Country            Phone 1               Phone 2  \
8   Robersonstad       Cyprus  854-138-4911x5772   +1-448-910-2276x729
9     Elaineberg  Timor-Leste   739.218.2516x459  001-054-401-0347x617
10  Shannonville     Guernsey   637-854-0256x825      114.336.0784x788

                      Email Subscription Date                      Website
8   mariokhan@ryan-pope.org        2020-01-13     https://www.bullock.net/
9         mdyer@escobar.net        2021-11-08           https://arias.com/
10       kirksalas@webb.com        2021-10-20  https://simmons-hurley.com/
            City                 Country
5  Chavezborough  Bosnia and Herzegovina
6       Lake Ana        Pitcairn Islands

### for Index wise Access - Iloc

In [6]:
df.iloc[:,[0,2]] 

#use at as an alternate

    Index First Name
0       1     Sheryl
1       2    Preston
2       3        Roy
3       4      Linda
4       5     Joanna
..    ...        ...
95     96       Karl
96     97       Lynn
97     98       Fred
98     99     Yvonne
99    100   Clarence

[100 rows x 2 columns]

#### Dataframes are mutable too

In [7]:
df.loc[1:3,"First Name"] = 'Nikita'
df.head(4)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Nikita,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Nikita,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Nikita,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/

#### Sorting

In [8]:
df.sort_values(["Country"]).head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
24,25,eC1927Ca84E033e,Shane,Wilcox,Tucker LLC,Bryanville,Albania,(429)005-9030x11004,541-116-4501,mariah88@santos.com,2021-04-06,https://www.ramos.com/
51,52,e898eEB1B9FE22b,Samuel,Crawford,"May, Goodwin and Martin",South Jasmine,Algeria,802-242-7457,626.116.9535x8578,xpittman@ritter-carney.net,2021-03-27,https://guerrero.org/
92,93,aAb6AFc7AfD0fF3,Collin,Ayers,Lamb-Peterson,South Lonnie,Anguilla,404-645-5351x012,001-257-582-8850x8516,dudleyemily@gonzales.biz,2021-06-29,http://www.ruiz.com/

## Filtering

In [13]:
df[df['Subscription Date']>'2022-01-01'].head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
14,15,6fEaA1b7cab7B6C,Faith,Lutz,Carter-Hancock,Burchbury,Singapore,(781)861-7180x8306,207-185-3665,cassieparrish@blevins-chapman.net,2022-01-26,http://stevenson.org/
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
17,18,F8Aa9d6DfcBeeF8,Greg,Mata,Valentine LLC,Lake Leslie,Mozambique,(701)087-2415,(195)156-1861x26241,jaredjuarez@carroll.org,2022-03-26,http://pitts-cherry.com/

In [20]:
df[df['First Name'].str.contains('Max')].head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
20,21,9F9AdB7B8A6f7F2,Maxwell,Frye,Patterson Inc,East Carly,Malta,423.262.3059,202-880-0688x7491,fgibson@drake-webb.com,2022-01-12,http://www.roberts.com/

In [25]:
df[df['Country'].isin(['Singapore','Oman'])].head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
14,15,6fEaA1b7cab7B6C,Faith,Lutz,Carter-Hancock,Burchbury,Singapore,(781)861-7180x8306,207-185-3665,cassieparrish@blevins-chapman.net,2022-01-26,http://stevenson.org/
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
83,84,78C06E9b6B3DF20,Chad,Davidson,Garcia-Jimenez,South Joshuashire,Oman,8275702958,(804)842-4715,justinwalters@jimenez.com,2021-11-15,http://www.garner-oliver.com/

In [26]:
df[df['Country'].isin(['Singapore','Oman']) & df['First Name'].str.contains('Mira')].head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/

In [27]:
df.query('Country == "Chile"')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/

## Add/Remove Columns

In [4]:
employee = pd.DataFrame([[1,'Fanny'],[2,'Luca'],[3,'Kimmy']], columns=['Id','Name'])

print(employee,end='\n\nAfter\n\n')

employee['Age']=[25,30,99]

print(employee,end='\n\nAfter\n\n')

employee.rename(columns={'Name':'First Name'}, inplace=True)

print(employee,end='\n\nAfter\n\n')

import numpy as np
employee['Salary']= np.where(employee['Age']>30, 200000, 400000)
employee['EmpId']=[12,67,23]
print(employee)

   Id   Name
0   1  Fanny
1   2   Luca
2   3  Kimmy

After

   Id   Name  Age
0   1  Fanny   25
1   2   Luca   30
2   3  Kimmy   99

After

   Id First Name  Age
0   1      Fanny   25
1   2       Luca   30
2   3      Kimmy   99

After

   Id First Name  Age  Salary  EmpId
0   1      Fanny   25  400000     12
1   2       Luca   30  400000     67
2   3      Kimmy   99  200000     23

In [5]:
employee.drop(columns=['EmpId'], inplace=True)
print(employee)

   Id First Name  Age  Salary
0   1      Fanny   25  400000
1   2       Luca   30  400000
2   3      Kimmy   99  200000

In [8]:
employee['Revenue']= employee['Salary']*100
employee

   Id First Name  Age  Salary   Revenue PaymentType
0   1      Fanny   25  400000  40000000      Online
1   2       Luca   30  400000  40000000      Online
2   3      Kimmy   99  200000  20000000        Cash

In [7]:
employee['PaymentType'] = employee['Salary'].apply(lambda x:'Cash' if x<300000 else ('Online' if x>300000 else ''))
employee

   Id First Name  Age  Salary   Revenue PaymentType
0   1      Fanny   25  400000  40000000      Online
1   2       Luca   30  400000  40000000      Online
2   3      Kimmy   99  200000  20000000        Cash

In [12]:
def calculate_pf(row):
    if row['Salary']>300000:
        return row['Salary']*(30/100)
    elif row['Salary']<300000:
        return row['Salary']*(10/100)
    
employee['Pf']= employee.apply(calculate_pf, axis=1) #1 is rows

employee

   Id First Name  Age  Salary   Revenue PaymentType        Pf
0   1      Fanny   25  400000  40000000      Online  120000.0
1   2       Luca   30  400000  40000000      Online  120000.0
2   3      Kimmy   99  200000  20000000        Cash   20000.0

## Merging and Concatenating Data

In [ ]:
Department = pd.DataFrame([[1,'Finance'],[2,'Tech'],[3,'HR']], columns=['EmpId', 'DName'])

#Joins!
emp_new=pd.merge(employee, Department, left_on='Id', right_on='EmpId', how='inner')
emp_new

   Id First Name  Age  Salary   Revenue PaymentType        Pf  EmpId    DName
0   1      Fanny   25  400000  40000000      Online  120000.0      1  Finance
1   2       Luca   30  400000  40000000      Online  120000.0      2     Tech
2   3      Kimmy   99  200000  20000000        Cash   20000.0      3       HR

In [14]:
tech = emp_new[emp_new['DName']=='Tech'].copy()
finance = emp_new[emp_new['DName']=='Finance'].copy()

new_df = pd.concat([tech, finance])
new_df

   Id First Name  Age  Salary   Revenue PaymentType        Pf  EmpId    DName
1   2       Luca   30  400000  40000000      Online  120000.0      2     Tech
0   1      Fanny   25  400000  40000000      Online  120000.0      1  Finance

### Handle Null Values

In [18]:
Department.loc[len(Department)]=[None,0] 
Department

   EmpId    DName
0    1.0  Finance
1    2.0     Tech
2    3.0       HR
3    NaN      0.0
4    NaN      0.0

In [34]:
print(Department[Department['EmpId'].isna()])
print(Department[Department['EmpId'].notna()])

#fillna
temp_dep=Department.fillna(10)
print(temp_dep)

#interplolate - just fill in missing based on surroundings
s= pd.Series([10,np.nan, 12,np.nan, np.nan, 40])
print(s.interpolate())

#dropna() - drop full entire rows

   EmpId DName
3    NaN   0.0
4    NaN   0.0
   EmpId    DName
0    1.0  Finance
1    2.0     Tech
2    3.0       HR
   EmpId    DName
0    1.0  Finance
1    2.0     Tech
2    3.0       HR
3   10.0      0.0
4   10.0      0.0
0    10.000000
1    11.000000
2    12.000000
3    21.333333
4    30.666667
5    40.000000
dtype: float64

## Aggregation

In [47]:
customer= pd.read_csv('customers-100.csv')
customer.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [ ]:
#find numbers by companies
customer['Country'].value_counts()
customer['Company'].value_counts()
#specifc
customer[customer['Country']=='Solomon Islands']['Company'].value_counts()

Company
Glover and Sons            1
Guzman-Brown               1
Lee, Lucero and Johnson    1
Schmitt-Jones              1
Name: count, dtype: int64

In [ ]:
print(customer.groupby('Company')) #returns a group by object

# for company, group in customer.groupby('Company'):
#     print(company)
#     print(group)
#     print()

print(customer.groupby('Company')['Country'].first())
print(customer.groupby('Company')['Country'].size())

<pandas.api.typing.DataFrameGroupBy object at 0x000001CF109E1370>
Company
Acosta, Petersen and Morrow                            Zimbabwe
Adkins-Salinas                                    Liechtenstein
Anderson Ltd                                             Poland
Beck-Hendrix                                        Timor-Leste
Blankenship-Arias                                    Micronesia
                                             ...
Ware, Burns and Oneal                                 Sri Lanka
Warren Ltd                          French Southern Territories
Waters, Chase and Aguilar                               Bahamas
Watts-Donaldson                Lao People's Democratic Republic
Winters-Mendoza                                  Western Sahara
Name: Country, Length: 99, dtype: str
Company
Acosta, Petersen and Morrow    1
Adkins-Salinas                 1
Anderson Ltd                   1
Beck-Hendrix                   1
Blankenship-Arias              1
                              ..
Ware, Burns and Oneal          1
Warren Ltd                     1
Waters, Chase and Aguilar      1
Watts-Donaldson                1
Winters-Mendoza                1
Name: Country, Length: 99, dtype: int64

In [ ]:
pivot = customer.pivot(columns='Company', index='Country', values='First Name')
pivot

pivot.loc['Solomon Islands']

Company
Acosta, Petersen and Morrow    NaN
Adkins-Salinas                 NaN
Anderson Ltd                   NaN
Beck-Hendrix                   NaN
Blankenship-Arias              NaN
                              ...
Ware, Burns and Oneal          NaN
Warren Ltd                     NaN
Waters, Chase and Aguilar      NaN
Watts-Donaldson                NaN
Winters-Mendoza                NaN
Name: Solomon Islands, Length: 99, dtype: str